Update erc20 precompile transfer to use extrinsic
futureversecom/trn-seed pull request #759
Opened 2023-12-08 09:30 UTC by KarishmaBothara

**PR checklist**  
Currently some precompiles call the trait internally rather than the extrinsic directly, such as ERC20-transfer. This means that if we block the assets-transfer extrinsic, the precompile will still function normally. If we want to be able to block precompiles with the maintenance-mode block_call extrinsic, these precompiles will need to change their implementation.

We can block precompile addresses from executing which can achieve similar results, however this may not give us the full flexibility we require

I have attached the precompile list which calls trait internally in the ticket

Update ERC20 precompile in this PR to use extrinsic over trait

Closes https://futureverse.atlassian.net/browse/TRN-166

- [x] Describe the added/changed/fixed/removed behaviour

2024-01-10 21:44 UTC, JasonTulp reviewed
Looks good! Just need to remove the double gas calculation :)

2024-01-10 21:44 UTC, JasonTulp commented on evm-precompiles/erc20/src/lib.rs
> -		let _ = <pallet_assets_ext::Pallet<Runtime> as Transfer<Runtime::AccountId>>::transfer(
We can remove the handle.record_cost above this which manually records the cost of the transfer extrinsic. By using try_dispatch we no longer need this

2024-01-10 21:44 UTC, JasonTulp commented on evm-precompiles/erc20/src/lib.rs
> -			let _ = <pallet_assets_ext::Pallet<Runtime> as Transfer<Runtime::AccountId>>::transfer(
Can remove the manual record_cost above this too

2024-01-10 21:44 UTC, JasonTulp commented on e2e/test/ERC20/Erc20.TxCosts.test.ts
> +    expect(precompileGasEstimate).to.be.greaterThan(contractGasEstimate);
Hopefully once the extra gas is removed this will go back to lessThan

2024-01-12 06:07 UTC, KarishmaBothara commented on e2e/test/ERC20/Erc20.TxCosts.test.ts
> +    expect(precompileGasEstimate).to.be.greaterThan(contractGasEstimate);
thanks.. yes, you were right.. it does solves this issue.. :)

2024-01-14 21:28 UTC, zees-dev commented on evm-precompiles/erc20/src/lib.rs
> +		let destination = to.clone().into();
not sure if we need rhe `.into()` here - as we dont explicitly define the converted type
```suggestion
		let destination = to.clone();
```

2024-01-14 21:29 UTC, zees-dev commented on e2e/.yarn/install-state.gz
remove this file? not sure why this is committed in.

2024-01-14 21:30 UTC, zees-dev requested changes
LGTM, minor changes required.
Also CI needs to be fixed/passing.

2024-01-15 04:36 UTC, KarishmaBothara commented on evm-precompiles/erc20/src/lib.rs
> +		let destination = to.clone().into();
this doesn't work without `.into()`
```
--> evm-precompiles/erc20/src/lib.rs:283:18
    |
283 |                 destination: to.clone(),
    |                              ^^^^^^^^^^ expected associated type, found `H160`
    |
    = note: expected associated type `<Runtime as frame_system::Config>::AccountId`
                        found struct `H160`
    = help: consider constraining the associated type `<Runtime as frame_system::Config>::AccountId` to `H160` or calling a method that returns `<Runtime as frame_system::Config>::AccountId`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
help: call `Into::into` on this expression to convert `H160` into `<Runtime as frame_system::Config>::AccountId`
    |
283 |                 destination: to.clone().into(),
    |                                        +++++++
```

2024-01-15 04:38 UTC, zees-dev commented on evm-precompiles/erc20/src/lib.rs
> +		let destination = to.clone().into();
Ah interesting, ok ignore the comment then 👍

2024-01-17 02:33 UTC, zees-dev approved these changes

2024-01-17 02:59 UTC, merged