Doughnuts
futureversecom/trn-seed pull request #760
Opened 2023-12-12 03:57 UTC by surangap

### Changelog
This PR will add the following functionality

- Add `pallet-doughnut` to support transaction execution with doughnuts
-

2024-02-15 21:44 UTC, JasonTulp commented on runtime/src/lib.rs
> +// }
Can remove this now?

2024-02-19 00:44 UTC, zees-dev commented on pallet/common/src/lib.rs
> +	) -> DispatchResult;
Lets make `DispatchResult` an associated type; in the case of XRPL - we use `bool`.
We should default it to boolean too? - but can be overriden.

2024-02-19 00:46 UTC, zees-dev commented on pallet/common/src/lib.rs
> +	type PermissionObject;
Need a more generic name here; in some cases this associated type may not be used (for example for XRPL).
Maybe `Extra` makes more sense here?

2024-02-19 01:08 UTC, zees-dev commented on pallet/common/src/lib.rs
> +	type PermissionObject;
Currently im using this for xrpl pallet:
```rust
/// Generic trait to validate extrinsics satisfy some condition
pub trait ExtrinsicChecker {
	type Call;
	type Extra = ();
	type Result = bool;
	fn check_extrinsic(call: &Self::Call, extra: &Self::Extra) -> Self::Result;
}
```

will require `#![feature(associated_type_defaults)]` at top of file (probably above the `#![cfg_attr(not(feature = "std"), no_std)]` until we upgrade our rust version.

2024-02-19 20:58 UTC, surangap commented on runtime/src/lib.rs
> +// }
5aebbb1

2024-02-19 20:59 UTC, surangap commented on pallet/common/src/lib.rs
> +	type PermissionObject;
80072d6

2024-02-19 21:02 UTC, JasonTulp commented on e2e/test/Doughnuts.test.ts
> +    console.log("\n====  Creating Doughnut");
nit. We should remove all these extra comments

2024-02-19 23:22 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +			let check = || {
nit, why use a closure for this?

2024-02-19 23:25 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +	pub fn check_self_contained(&self) -> Option<Result<H160, TransactionValidityError>> {
I feel like some of the checks in check_self_contained are redundant. i.e. We are decoding the doughnut 4 times within check_self_contained, validate_self_contained apply_self_contained and transact. Is there a way to combine validate and check? (Maybe I'm misunderstanding the purpose of the two separate methods)

2024-02-20 00:10 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +	pub fn check_self_contained(&self) -> Option<Result<H160, TransactionValidityError>> {
Maybe instead we can separate out the common checks and calculations within validate and apply (i.e. getting fee_payer, genesis hash etc) into a helper function to reduce duplicate code?

2024-02-20 00:11 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +			<DoughnutFeePayerValidations<T> as SignedExtension>::post_dispatch(
Do we need post_dispatch to be called on the sender as well?

2024-02-20 00:12 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +	/// Map from collection to its public minting information
Oops, I think this was me, but this comment is wrong 
```suggestion
	/// Map doughnut hash to blocked status
```

2024-02-20 00:13 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +		WhitelistedHoldersUpdated { holder: T::AccountId, enabled: bool },
Nit. Need doc comments for events

2024-02-20 00:13 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +	#[pallet::hooks]
Can take this out

2024-02-20 00:16 UTC, JasonTulp commented on pallet/doughnut/src/lib.rs
> +/// Checks performed on a fee payer of a Doughnut transaction
Nit. Can we put this at the top of the file? Will make it easier to keep track of

2024-02-20 00:17 UTC, JasonTulp commented on pallet/doughnut/src/test.rs
> +		println!("holder address (Alice): {:?}", to_hex(holder.address().0.as_slice(), false));
Nit. Should probably remove these comments now

2024-02-20 00:19 UTC, JasonTulp commented on runtime/Cargo.toml
> +#doughnut-rs = { path = "../../../trn-doughnut-rs", default-features = false, features = ["crypto"] }
```suggestion
```

2024-02-20 00:21 UTC, JasonTulp commented on runtime/src/impls.rs
> +		}
To remove the warning we can do something like this:
```suggestion
		let call: Self::Call = &call {
			RuntimeCall::Futurepass(pallet_futurepass::Call::proxy_extrinsic {
				call: inner_call,
				..
			}) => *inner_call.clone(),
			RuntimeCall::FeeProxy(pallet_fee_proxy::Call::call_with_fee_preferences {
				call: inner_call_1,
				..
			}) => {
				if let RuntimeCall::Futurepass(pallet_futurepass::Call::proxy_extrinsic {
					call: inner_call_2,
					..
				}) = *inner_call_1.clone()
				{
					*inner_call_2.clone();
				} else {
					*inner_call_1.clone();
				}
			},
			_ => call.clone(),
		}
```

2024-02-20 00:23 UTC, JasonTulp commented on runtime/src/impls.rs
> +			RuntimeCall::Balances(pallet_balances::Call::transfer { dest, value }) => {
Ideally we'd use AssetsExt transfer for these (to support any asset + balances) But maybe a job for the next iteration

2024-02-20 00:25 UTC, JasonTulp approved these changes
Lgtm! 🚀 Left a few comments, but nothing that should block merging (Can push to next update)

2024-02-20 01:32 UTC, zees-dev commented on e2e/common/index.ts
> +export const ALICE_PRIVATE_KEY = "0xcb6df9de1efca7a3998a8ead4e02159d5fa99c3e0d4fd6432667390bb4726854";
Isn't ALITH and BOB enough?

2024-02-20 01:33 UTC, zees-dev commented on e2e/test/Doughnuts.test.ts
need to remove all console.logs - or comment them out.
Makes debugging broken test in CI more difficult

2024-02-20 01:35 UTC, zees-dev commented on pallet/doughnut/src/benchmarking.rs
> +		let doughnut_encoded = hex!("011800020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a10390084fdbf27d2b79d26a4f13f0ccd982cb755a661969143c37cbc49ef5b91f27000000000074726e00000000000000
would be good to construct this if we can; so we know how the value is derived

2024-02-20 01:35 UTC, zees-dev commented on pallet/doughnut/src/mock.rs
> +impl pallet_transaction_payment::Config for Test {
can we not use the macro instead?

2024-02-20 01:39 UTC, zees-dev commented on runtime/src/lib.rs
> +		Doughnut: pallet_doughnut = 48,
may need to be changed due to xrpl pallet being merged first

2024-02-20 01:40 UTC, zees-dev approved these changes
Minor changes required; no blocker from my POV.

Note: THE XRPL pallet has been merged first; so changes/updates will be required here.
Note: We also need to merge the dependent PRs first, tag and release, then reference the released crate versions instead.

2024-02-20 05:58 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +			let check = || {
copied code from ethereum pallet :D

2024-02-20 06:08 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +	pub fn check_self_contained(&self) -> Option<Result<H160, TransactionValidityError>> {
regarding decoding of doughnut 4 times, we don't have a workaround atm. no way to pass the decoded doughnut downstream due to trait restrictions.
But we can add a common function to include all the common validations.

2024-02-20 06:23 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +			<DoughnutFeePayerValidations<T> as SignedExtension>::post_dispatch(
doesn't matter. anw added for consistency

2024-02-20 06:41 UTC, surangap commented on runtime/src/impls.rs
> +			RuntimeCall::Balances(pallet_balances::Call::transfer { dest, value }) => {
yeah, need a discussion to select the whitelist

2024-02-20 06:49 UTC, surangap commented on e2e/common/index.ts
> +export const ALICE_PRIVATE_KEY = "0xcb6df9de1efca7a3998a8ead4e02159d5fa99c3e0d4fd6432667390bb4726854";
Alice to bob test cases in early tests I think

2024-02-20 07:07 UTC, surangap commented on pallet/doughnut/src/mock.rs
> +impl pallet_transaction_payment::Config for Test {
tried this, there were more dependent pallets required to use the macro

2024-02-20 07:09 UTC, surangap commented on runtime/src/lib.rs
> +		Doughnut: pallet_doughnut = 48,
`48` looks good

2024-02-20 07:11 UTC, surangap commented on e2e/test/Doughnuts.test.ts
> +    console.log("\n====  Creating Doughnut");
[62e90bf](https://github.com/futureversecom/trn-seed/pull/760/commits/62e90bf935de42565c9a51b52f1e6c1fd2f680a8)

2024-02-20 07:12 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +			<DoughnutFeePayerValidations<T> as SignedExtension>::post_dispatch(
[62e90bf](https://github.com/futureversecom/trn-seed/pull/760/commits/62e90bf935de42565c9a51b52f1e6c1fd2f680a8)

2024-02-20 07:12 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +	/// Map from collection to its public minting information
[62e90bf](https://github.com/futureversecom/trn-seed/pull/760/commits/62e90bf935de42565c9a51b52f1e6c1fd2f680a8)

2024-02-20 07:12 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +		WhitelistedHoldersUpdated { holder: T::AccountId, enabled: bool },
[ffd4629](https://github.com/futureversecom/trn-seed/pull/760/commits/ffd4629851906371c80514b54a79229c864f3b63)

2024-02-20 07:12 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +/// Checks performed on a fee payer of a Doughnut transaction
[ffd4629](https://github.com/futureversecom/trn-seed/pull/760/commits/ffd4629851906371c80514b54a79229c864f3b63)

2024-02-20 07:13 UTC, surangap commented on pallet/doughnut/src/test.rs
> +		println!("holder address (Alice): {:?}", to_hex(holder.address().0.as_slice(), false));
[ffd4629](https://github.com/futureversecom/trn-seed/pull/760/commits/ffd4629851906371c80514b54a79229c864f3b63)

2024-02-20 07:13 UTC, surangap commented on runtime/Cargo.toml
> +#doughnut-rs = { path = "../../../trn-doughnut-rs", default-features = false, features = ["crypto"] }
[ffd4629](https://github.com/futureversecom/trn-seed/pull/760/commits/ffd4629851906371c80514b54a79229c864f3b63)

2024-02-20 07:13 UTC, surangap commented on runtime/src/impls.rs
> +		}
[ffd4629](https://github.com/futureversecom/trn-seed/pull/760/commits/ffd4629851906371c80514b54a79229c864f3b63)

2024-02-20 07:14 UTC, surangap commented on pallet/doughnut/src/benchmarking.rs
> +		let doughnut_encoded = hex!("011800020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a10390084fdbf27d2b79d26a4f13f0ccd982cb755a661969143c37cbc49ef5b91f27000000000074726e00000000000000
[d233d1c](https://github.com/futureversecom/trn-seed/pull/760/commits/d233d1c9293f61988dee4afda3c0f9be12741b94)

2024-02-20 07:14 UTC, surangap commented on e2e/test/Doughnuts.test.ts
[62e90bf](https://github.com/futureversecom/trn-seed/pull/760/commits/62e90bf935de42565c9a51b52f1e6c1fd2f680a8)

2024-02-20 08:00 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +	pub fn check_self_contained(&self) -> Option<Result<H160, TransactionValidityError>> {
[5fba5ce](https://github.com/futureversecom/trn-seed/pull/760/commits/5fba5ce21a3b4bb432261eee8351ab63f65716db)

2024-02-20 20:57 UTC, JasonTulp approved these changes

2024-02-20 21:15 UTC, zees-dev commented on pallet/doughnut/src/lib.rs
> +		DoughnutCallExecuted { result: DispatchResult },
This should contain more details I think, i.e. holder, issuer, permissions, etc.
Anything you think would be useful to offchain services; I think we'd like to track this data to know which holders are using the doughnuts.

2024-02-20 21:16 UTC, zees-dev commented on pallet/doughnut/src/lib.rs
> +		pub fn revoke_holder(
Same here, remember to emit the event.

2024-02-20 21:17 UTC, zees-dev requested changes
Will approve after we get the event changes in - which seem to be quite important imo.

Otherwise looks good!

2024-02-20 23:13 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +		DoughnutCallExecuted { result: DispatchResult },
[52cd04c](https://github.com/futureversecom/trn-seed/pull/760/commits/52cd04c6077ca696e0f3f20d269d43e84c1bace4)

2024-02-20 23:13 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +		pub fn revoke_doughnut(
[52cd04c](https://github.com/futureversecom/trn-seed/pull/760/commits/52cd04c6077ca696e0f3f20d269d43e84c1bace4)

2024-02-20 23:13 UTC, surangap commented on pallet/doughnut/src/lib.rs
> +		pub fn revoke_holder(
[52cd04c](https://github.com/futureversecom/trn-seed/pull/760/commits/52cd04c6077ca696e0f3f20d269d43e84c1bace4)

2024-02-21 02:19 UTC, JasonTulp commented on runtime/src/impls.rs
> +			RuntimeCall::AssetsExt(pallet_assets_ext::Call::transfer {
Nice :+1: This will be useful

2024-02-21 02:22 UTC, JasonTulp approved these changes
Looks good, cheers for adding AssetsExt::transfer + expiry validation

2024-02-21 03:10 UTC, zees-dev approved these changes
LGTM!

2024-02-21 03:36 UTC, merged