TRN-397 erc20-peg method for sudo to claim delayed payments
futureversecom/trn-seed pull request #885
Opened 2024-10-02 20:28 UTC by Nick95550

**PR checklist**  

When upgrading to Frame V2 we had to introduce a bounded vec into the erc20-peg pallet storing the delayed payments. This is a potentially vulnerability and so we should mitigate the impact this has and potentially remedies. This PR introduces a extrinsic allowing sudo to claim a delayed payment in the case that a payment gets blocked.

related ticket: https://futureverse.atlassian.net/jira/software/c/projects/TRN/boards/39?assignee=712020:e6af0fd1-96ad-49ff-8750-5ff03ad831e8&selectedIssue=TRN-397

- [X] Describe the added/changed/fixed/removed behaviour
- [X] Tag related issue(s)
- [ ] Add appropriate unit tests and/or integration tests to the [integration test repository](https://github.com/futureversecom/seed-integration-tests)

2024-10-09 22:31 UTC, JasonTulp reviewed
Looks good man! Thanks heaps for doing this. Nice work on the migration too, they can be tricky

2024-10-09 22:31 UTC, JasonTulp commented on runtime/src/migrations/erc20_peg.rs
> +				);
At the end of the test, the StorageMap should be able to decode the type properly using the standard get method, so you can use standard gets here
```suggestion
				assert_eq!(
					DelayedPaymentSchedule::<Runtime>::get(one),
					expected_delayed_payment_1
				);
				assert_eq!(
					DelayedPaymentSchedule::<Runtime>::get(two),
					expected_delayed_payment_2
				);
```

2024-10-13 20:59 UTC, JasonTulp approved these changes
lgtm! Nice work

2024-10-13 22:25 UTC, zees-dev commented on pallet/erc20-peg/src/lib.rs
> +		.map_err(|_| Error::<T>::PaymentIdNotFound)?;
nit:
```suggestion
		DelayedPaymentSchedule::<T>::try_mutate(block_number, |payment_ids| 
            payment_ids.remove_item(&payment_id).ok_or(())
        ).map_err(|_| Error::<T>::PaymentIdNotFound)?;
```

2024-10-13 22:30 UTC, zees-dev commented on pallet/erc20-peg/src/weights.rs
The weight differences in this file appear to be very large.
You need to use the https://github.com/futureversecom/trn-seed/actions/workflows/dispatch-benchmarking.yml GH workflow - from the PR branch, for `pallet-erc20-peg`

2024-10-13 22:31 UTC, zees-dev commented on runtime/src/weights/pallet_erc20_peg.rs
weights will be regenerated by the workflow

2024-10-13 22:32 UTC, zees-dev commented on runtime/src/migrations/erc20_peg.rs
> +			weight += v1::migrate_k::<Runtime>();
I beleive the previous migrations target onchain version 0; this one will target onchain version v1 (so the if condition above needs to be updated, and the previous migration removed?)

2024-10-13 22:42 UTC, zees-dev requested changes
Changes required for weights and update to migration code.

2024-10-15 00:01 UTC, Nick95550 commented on pallet/erc20-peg/src/lib.rs
> +		.map_err(|_| Error::<T>::PaymentIdNotFound)?;
Im not sure a remove_item is defined

2024-10-15 00:03 UTC, zees-dev commented on pallet/erc20-peg/src/lib.rs
> +		.map_err(|_| Error::<T>::PaymentIdNotFound)?;
Ah maybe it's trait import to extend iter type. 
Ok in this case ignore.

2024-10-15 00:22 UTC, JasonTulp commented on runtime/src/migrations/erc20_peg.rs
> +			weight += v1::migrate_k::<Runtime>();
I think how it is should be correct (Going from version 0 to 1) as both migrations are happening in the same runtime upgrade (8.60.0) The migration code above is from Karishma's PR [here](https://github.com/futureversecom/trn-seed/pull/887) which hasn't been deployed yet

2024-10-15 07:15 UTC, zees-dev approved these changes

2024-10-15 20:02 UTC, merged